### ISSUE TITLE
[CLI] Zoom being parsed as string instead of integer

### ISSUE THREAD

**Issue by shmugoh** [shmugoh/sv-dlp#38]
```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\sv-dlp.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\sv_dlp\__main__.py", line 140, in main
    img = sv_dlp.download_panorama(pano_id=pano, lat=lat, lng=lng, zoom=zoom)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\sv_dlp\__init__.py", line 153, in download_panorama
    tile_arr = self.service._build_tile_arr(self.metadata, zoom)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\sv_dlp\services\yandex.py", line 179, in _build_tile_arr
    zoom = max_zoom - zoom
           ~~~~~~~~~^~~~~~
TypeError: unsupported operand type(s) for -: 'int' and 'str'
```

```python
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\sv-dlp.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\sv_dlp\__main__.py", line 140, in main
    img = sv_dlp.download_panorama(pano_id=pano, lat=lat, lng=lng, zoom=zoom)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\sv_dlp\__init__.py", line 153, in download_panorama
    tile_arr = self.service._build_tile_arr(self.metadata, zoom)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\sv_dlp\services\google\__init__.py", line 209, in _build_tile_arr
    x_axis = metadata.size[0][zoom][0][1] // metadata.size[1][1]
             ~~~~~~~~~~~~~~~~^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by shmugoh** [comment]
fixed. will be released to prod in december update
